<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_farm
 *
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
namespace FarmNamespace\Component\Farm\Administrator\Model;
\defined('_JEXEC') or die;

use JFactory;
use Joomla\CMS\Date\Date;
use Joomla\CMS\Factory;
use Joomla\CMS\MVC\Model\AdminModel;
use Joomla\Database\DatabaseDriver;
use SurveyNamespace\Component\Surveys\Administrator\Table\SurveyLineTable;
/**
 * Item Model for a Survey.
 *
 * @since  1.0.0
 */
class EquipmentModel extends AdminModel
{
	/**
	 * The type alias for this content type.
	 *
	 * @var    string
	 * @since  1.0.0
	 */
	public $typeAlias = 'com_farm.equipment';
	/**
	 * Method to get the row form.
	 *
	 * @param   array    $data      Data for the form.
	 * @param   boolean  $loadData  True if the form is to load its own data (default case), false if not.
	 *
	 * @return  \JForm|boolean  A \JForm object on success, false on failure
	 *
	 * @since   1.0.0
	 */
	public function getForm($data = [], $loadData = true)
	{
		// Get the form.
		$form = $this->loadForm($this->typeAlias, 'farmequipment', ['control' => 'jform', 'load_data' => $loadData]);
		if (empty($form)) {
			return false;
		}
		return $form;
	}

	/**
	 * Method to get the data that should be injected in the form.
	 *
	 * @return  mixed  The data for the form.
	 *
	 * @since   1.0.0
	 */
	protected function loadFormData()
	{
		$app = Factory::getApplication();
		$data = $this->getItem();
		$this->preprocessData($this->typeAlias, $data);
		return $data;
	}

	public function save($data)
	{
		$user =& JFactory::getUser()->id;
		$currentTime = new Date('now');
		$currentTime = $currentTime->toSql();

		if (empty($data["id"]))
		{
			$data["created"]= $currentTime;
			$data["created_by"] = $user;
		}
		$data["modified"] = $currentTime;
		$data["modified_by"] = $user;

		return parent::save($data); // TODO: Change the autogenerated stub
	}

}
